[features]
seeds = false
[programs.localnet]
mysolanaapp2 = "21RuzWEaWi1AvsMKhQYJGmrFcZRvsz3NLRFURLTRhQwB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/otp/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
